CREATE DATABASE IF NOT EXISTS LOJA_CELULAR;
USE LOJA_CELULAR;

CREATE TABLE IF NOT EXISTS PRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(20) NOT NULL UNIQUE,
  MARCA VARCHAR(20) NOT NULL,
  PRECO DECIMAL(6,2) NOT NULL
  );

CREATE TABLE IF NOT EXISTS FORNECEDOR(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(20) NOT NULL UNIQUE,
  TELEFONE VARCHAR(20) NOT NULL,
  RUA VARCHAR(20) NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  BAIRRO VARCHAR(20) NOT NULL,
  CIDADE VARCHAR(20) NOT NULL,
  UF VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS DEPOSITO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(20) NOT NULL UNIQUE,
  TELEFONE VARCHAR(20) NOT NULL,
  RUA VARCHAR(20) NOT NULL,
  NUMERO VARCHAR(20) NOT NULL,
  BAIRRO VARCHAR(20) NOT NULL,
  CIDADE VARCHAR(20) NOT NULL,
  UF VARCHAR(2) NOT NULL
);


CREATE TABLE IF NOT EXISTS FORNECEDORPRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FORNECEDORID INT NOT NULL,
  PRODUTOID INT NOT NULL,
  CONSTRAINT FK_ID_FORNECEDOR_FP FOREIGN KEY (FORNECEDORID) REFERENCES FORNECEDOR (ID),
  CONSTRAINT FK_ID_PRODUTO_FP FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO(ID)
);

CREATE TABLE IF NOT EXISTS DEPOSITOPRODUTO(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DEPOSITOID INT NOT NULL,
  PRODUTOID INT NOT NULL,
  PONTOREPOSICAO INT NOT NULL,
  QUANTIDADEATUAL INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_DP FOREIGN KEY (DEPOSITOID) REFERENCES DEPOSITO (ID),
  CONSTRAINT FK_ID_PRODUTO_DP FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO (ID)
);

CREATE TABLE IF NOT EXISTS MOVIMENTACAO (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DEPOSITOID INT NOT NULL,
  PRODUTOID INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  TIPO INT NOT NULL,
  CONSTRAINT FK_ID_DEPOSITO_M FOREIGN KEY (DEPOSITOID) REFERENCES DEPOSITO (ID),
  CONSTRAINT FK_ID_PRODUTO_M FOREIGN KEY (PRODUTOID) REFERENCES PRODUTO (ID)
);
